[package]
name = "rust-2020"
version = "0.1.0"
authors = ["Bradley Mackey <bradleymackey@me.com>"]
edition = "2018"

[dependencies]
regex = "1.4.2"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
num = "0.3.1"
